/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsWeeksViewRouteImport } from './routes/docs/weeks-view'
import { Route as DocsStylingRouteImport } from './routes/docs/styling'
import { Route as DocsSelectionModesRouteImport } from './routes/docs/selection-modes'
import { Route as DocsQuickStartRouteImport } from './routes/docs/quick-start'
import { Route as DocsMonthViewRouteImport } from './routes/docs/month-view'
import { Route as DocsIntroductionRouteImport } from './routes/docs/introduction'
import { Route as DocsDatesAndFormatsRouteImport } from './routes/docs/dates-and-formats'
import { Route as DocsCompositionRouteImport } from './routes/docs/composition'
import { Route as DocsCalendarProviderRouteImport } from './routes/docs/calendar-provider'
import { Route as DocsAccessibilityRouteImport } from './routes/docs/accessibility'
import { Route as DocsApiSymbolRouteImport } from './routes/docs/api/$symbol'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWeeksViewRoute = DocsWeeksViewRouteImport.update({
  id: '/weeks-view',
  path: '/weeks-view',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStylingRoute = DocsStylingRouteImport.update({
  id: '/styling',
  path: '/styling',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSelectionModesRoute = DocsSelectionModesRouteImport.update({
  id: '/selection-modes',
  path: '/selection-modes',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickStartRoute = DocsQuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMonthViewRoute = DocsMonthViewRouteImport.update({
  id: '/month-view',
  path: '/month-view',
  getParentRoute: () => DocsRoute,
} as any)
const DocsIntroductionRoute = DocsIntroductionRouteImport.update({
  id: '/introduction',
  path: '/introduction',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDatesAndFormatsRoute = DocsDatesAndFormatsRouteImport.update({
  id: '/dates-and-formats',
  path: '/dates-and-formats',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCompositionRoute = DocsCompositionRouteImport.update({
  id: '/composition',
  path: '/composition',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCalendarProviderRoute = DocsCalendarProviderRouteImport.update({
  id: '/calendar-provider',
  path: '/calendar-provider',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAccessibilityRoute = DocsAccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiSymbolRoute = DocsApiSymbolRouteImport.update({
  id: '/api/$symbol',
  path: '/api/$symbol',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/accessibility': typeof DocsAccessibilityRoute
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/composition': typeof DocsCompositionRoute
  '/docs/dates-and-formats': typeof DocsDatesAndFormatsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/selection-modes': typeof DocsSelectionModesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs/accessibility': typeof DocsAccessibilityRoute
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/composition': typeof DocsCompositionRoute
  '/docs/dates-and-formats': typeof DocsDatesAndFormatsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/selection-modes': typeof DocsSelectionModesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/accessibility': typeof DocsAccessibilityRoute
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/composition': typeof DocsCompositionRoute
  '/docs/dates-and-formats': typeof DocsDatesAndFormatsRoute
  '/docs/introduction': typeof DocsIntroductionRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/quick-start': typeof DocsQuickStartRoute
  '/docs/selection-modes': typeof DocsSelectionModesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/docs/accessibility'
    | '/docs/calendar-provider'
    | '/docs/composition'
    | '/docs/dates-and-formats'
    | '/docs/introduction'
    | '/docs/month-view'
    | '/docs/quick-start'
    | '/docs/selection-modes'
    | '/docs/styling'
    | '/docs/weeks-view'
    | '/docs/'
    | '/docs/api/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs/accessibility'
    | '/docs/calendar-provider'
    | '/docs/composition'
    | '/docs/dates-and-formats'
    | '/docs/introduction'
    | '/docs/month-view'
    | '/docs/quick-start'
    | '/docs/selection-modes'
    | '/docs/styling'
    | '/docs/weeks-view'
    | '/docs'
    | '/docs/api/$symbol'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs'
    | '/docs/accessibility'
    | '/docs/calendar-provider'
    | '/docs/composition'
    | '/docs/dates-and-formats'
    | '/docs/introduction'
    | '/docs/month-view'
    | '/docs/quick-start'
    | '/docs/selection-modes'
    | '/docs/styling'
    | '/docs/weeks-view'
    | '/docs/'
    | '/docs/api/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/weeks-view': {
      id: '/docs/weeks-view'
      path: '/weeks-view'
      fullPath: '/docs/weeks-view'
      preLoaderRoute: typeof DocsWeeksViewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/styling': {
      id: '/docs/styling'
      path: '/styling'
      fullPath: '/docs/styling'
      preLoaderRoute: typeof DocsStylingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/selection-modes': {
      id: '/docs/selection-modes'
      path: '/selection-modes'
      fullPath: '/docs/selection-modes'
      preLoaderRoute: typeof DocsSelectionModesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quick-start': {
      id: '/docs/quick-start'
      path: '/quick-start'
      fullPath: '/docs/quick-start'
      preLoaderRoute: typeof DocsQuickStartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/month-view': {
      id: '/docs/month-view'
      path: '/month-view'
      fullPath: '/docs/month-view'
      preLoaderRoute: typeof DocsMonthViewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/introduction': {
      id: '/docs/introduction'
      path: '/introduction'
      fullPath: '/docs/introduction'
      preLoaderRoute: typeof DocsIntroductionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dates-and-formats': {
      id: '/docs/dates-and-formats'
      path: '/dates-and-formats'
      fullPath: '/docs/dates-and-formats'
      preLoaderRoute: typeof DocsDatesAndFormatsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/composition': {
      id: '/docs/composition'
      path: '/composition'
      fullPath: '/docs/composition'
      preLoaderRoute: typeof DocsCompositionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/calendar-provider': {
      id: '/docs/calendar-provider'
      path: '/calendar-provider'
      fullPath: '/docs/calendar-provider'
      preLoaderRoute: typeof DocsCalendarProviderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/accessibility': {
      id: '/docs/accessibility'
      path: '/accessibility'
      fullPath: '/docs/accessibility'
      preLoaderRoute: typeof DocsAccessibilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/$symbol': {
      id: '/docs/api/$symbol'
      path: '/api/$symbol'
      fullPath: '/docs/api/$symbol'
      preLoaderRoute: typeof DocsApiSymbolRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAccessibilityRoute: typeof DocsAccessibilityRoute
  DocsCalendarProviderRoute: typeof DocsCalendarProviderRoute
  DocsCompositionRoute: typeof DocsCompositionRoute
  DocsDatesAndFormatsRoute: typeof DocsDatesAndFormatsRoute
  DocsIntroductionRoute: typeof DocsIntroductionRoute
  DocsMonthViewRoute: typeof DocsMonthViewRoute
  DocsQuickStartRoute: typeof DocsQuickStartRoute
  DocsSelectionModesRoute: typeof DocsSelectionModesRoute
  DocsStylingRoute: typeof DocsStylingRoute
  DocsWeeksViewRoute: typeof DocsWeeksViewRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSymbolRoute: typeof DocsApiSymbolRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAccessibilityRoute: DocsAccessibilityRoute,
  DocsCalendarProviderRoute: DocsCalendarProviderRoute,
  DocsCompositionRoute: DocsCompositionRoute,
  DocsDatesAndFormatsRoute: DocsDatesAndFormatsRoute,
  DocsIntroductionRoute: DocsIntroductionRoute,
  DocsMonthViewRoute: DocsMonthViewRoute,
  DocsQuickStartRoute: DocsQuickStartRoute,
  DocsSelectionModesRoute: DocsSelectionModesRoute,
  DocsStylingRoute: DocsStylingRoute,
  DocsWeeksViewRoute: DocsWeeksViewRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSymbolRoute: DocsApiSymbolRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
