/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsWeeksViewRouteImport } from './routes/docs/weeks-view'
import { Route as DocsMonthViewRouteImport } from './routes/docs/month-view'
import { Route as DocsGettingStartedRouteImport } from './routes/docs/getting-started'
import { Route as DocsCalendarProviderRouteImport } from './routes/docs/calendar-provider'
import { Route as DocsApiSymbolRouteImport } from './routes/docs/api/$symbol'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWeeksViewRoute = DocsWeeksViewRouteImport.update({
  id: '/weeks-view',
  path: '/weeks-view',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMonthViewRoute = DocsMonthViewRouteImport.update({
  id: '/month-view',
  path: '/month-view',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCalendarProviderRoute = DocsCalendarProviderRouteImport.update({
  id: '/calendar-provider',
  path: '/calendar-provider',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiSymbolRoute = DocsApiSymbolRouteImport.update({
  id: '/api/$symbol',
  path: '/api/$symbol',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/calendar-provider': typeof DocsCalendarProviderRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/month-view': typeof DocsMonthViewRoute
  '/docs/weeks-view': typeof DocsWeeksViewRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/api/$symbol': typeof DocsApiSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/docs'
    | '/docs/calendar-provider'
    | '/docs/getting-started'
    | '/docs/month-view'
    | '/docs/weeks-view'
    | '/docs/'
    | '/docs/api/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/docs/calendar-provider'
    | '/docs/getting-started'
    | '/docs/month-view'
    | '/docs/weeks-view'
    | '/docs'
    | '/docs/api/$symbol'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/docs'
    | '/docs/calendar-provider'
    | '/docs/getting-started'
    | '/docs/month-view'
    | '/docs/weeks-view'
    | '/docs/'
    | '/docs/api/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/weeks-view': {
      id: '/docs/weeks-view'
      path: '/weeks-view'
      fullPath: '/docs/weeks-view'
      preLoaderRoute: typeof DocsWeeksViewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/month-view': {
      id: '/docs/month-view'
      path: '/month-view'
      fullPath: '/docs/month-view'
      preLoaderRoute: typeof DocsMonthViewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/calendar-provider': {
      id: '/docs/calendar-provider'
      path: '/calendar-provider'
      fullPath: '/docs/calendar-provider'
      preLoaderRoute: typeof DocsCalendarProviderRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api/$symbol': {
      id: '/docs/api/$symbol'
      path: '/api/$symbol'
      fullPath: '/docs/api/$symbol'
      preLoaderRoute: typeof DocsApiSymbolRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsCalendarProviderRoute: typeof DocsCalendarProviderRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsMonthViewRoute: typeof DocsMonthViewRoute
  DocsWeeksViewRoute: typeof DocsWeeksViewRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsApiSymbolRoute: typeof DocsApiSymbolRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCalendarProviderRoute: DocsCalendarProviderRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsMonthViewRoute: DocsMonthViewRoute,
  DocsWeeksViewRoute: DocsWeeksViewRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsApiSymbolRoute: DocsApiSymbolRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
