// @generated by scripts/generate-formats.ts — do not edit manually

import { CalendarProvider } from "../calendar-provider";
import { RangeEndDragHandle, RangeStartDragHandle } from "../drag-handle";
import {
  DayButton,
  DayCellTemplate,
  Grid,
  GridBody,
  WeekTemplate,
} from "../grid";
import { GridHeader, GridHeaderCell } from "../grid-header";
import { MonthView } from "../month-view";
import {
  DateString,
  MonthYearString,
  NextMonthButton,
  PrevMonthButton,
  TimeString,
} from "../navigation";
import { RangePreview } from "../range-preview";
import { RangeSelected } from "../selected-range";
import { WeekNumberCell, WeekNumberHeader } from "../week-number";

type F = "PlainDate";

const _CalendarProvider = CalendarProvider<F>;
const _DateString = DateString<F>;
const _DayButton = DayButton<F>;
const _DayCellTemplate = DayCellTemplate<F>;
const _Grid = Grid<F>;
const _GridBody = GridBody<F>;
const _GridHeader = GridHeader<F>;
const _GridHeaderCell = GridHeaderCell<F>;
const _MonthView = MonthView<F>;
const _MonthYearString = MonthYearString<F>;
const _NextMonthButton = NextMonthButton<F>;
const _PrevMonthButton = PrevMonthButton<F>;
const _RangeEndDragHandle = RangeEndDragHandle<F>;
const _RangePreview = RangePreview<F>;
const _RangeSelected = RangeSelected<F>;
const _RangeStartDragHandle = RangeStartDragHandle<F>;
const _TimeString = TimeString<F>;
const _WeekNumberCell = WeekNumberCell<F>;
const _WeekNumberHeader = WeekNumberHeader<F>;
const _WeekTemplate = WeekTemplate<F>;

export {
  _CalendarProvider as CalendarProvider,
  _DateString as DateString,
  _DayButton as DayButton,
  _DayCellTemplate as DayCellTemplate,
  _Grid as Grid,
  _GridBody as GridBody,
  _GridHeader as GridHeader,
  _GridHeaderCell as GridHeaderCell,
  _MonthView as MonthView,
  _MonthYearString as MonthYearString,
  _NextMonthButton as NextMonthButton,
  _PrevMonthButton as PrevMonthButton,
  _RangeEndDragHandle as RangeEndDragHandle,
  _RangePreview as RangePreview,
  _RangeSelected as RangeSelected,
  _RangeStartDragHandle as RangeStartDragHandle,
  _TimeString as TimeString,
  _WeekNumberCell as WeekNumberCell,
  _WeekNumberHeader as WeekNumberHeader,
  _WeekTemplate as WeekTemplate,
};
